version: '3.8'

services:

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timesheet_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/.env:/var/www/html/.env
      - ./Modules:/var/www/html/Modules
    networks:
      - timesheet-network
    depends_on:
      - database
      - redis

  nginx_landing:
    image: nginx:alpine
    container_name: nginx_landing
    restart: unless-stopped
    volumes:
      - ./docker/nginx/landing/default.conf:/etc/nginx/conf.d/default.conf
      - ./landing:/var/www/landing
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - timesheet-network

  nginx_api:
    image: nginx:alpine
    container_name: timesheet_nginx_api
    restart: unless-stopped
    depends_on:
      - app
    expose:
      - "80"
    volumes:
      - ./docker/nginx/api:/etc/nginx/conf.d
      - ./backend:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      timesheet-network:
        aliases:
          - webserver       # ðŸ‘ˆ MUITO IMPORTANTE: casa com o proxy_pass http://webserver

  nginx_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://api.vendaslive.com"
        VITE_APP_URL: "https://vendaslive.com"
    image: timesheet-frontend
    container_name: timesheet_nginx_app
    restart: unless-stopped
    depends_on:
      - nginx_api          # ðŸ‘ˆ frontend sÃ³ sobe depois do webserver estar pronto
    volumes:
      - ./docker/nginx/app/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - timesheet-network

  database:
    image: mysql:8.0
    container_name: timesheet_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: timesheet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: timesheet
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - timesheet-network

  redis:
    image: redis:alpine
    container_name: timesheet_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - timesheet-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./backend/redis/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  timesheet-network:
    driver: bridge

volumes:
  mysql_data:
